spring.application.name=UserService

spring.datasource.url=jdbc:postgresql://${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.liquibase.enabled=true

spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

encryption.key=${ENCRYPTION_KEY}


spring.security.oauth2.client.registration.keycloak.provider=keycloak
spring.security.oauth2.client.registration.keycloak.client-id=iw-user-service-client
spring.security.oauth2.client.registration.keycloak.client-secret= <SECRET_VALUE>
spring.security.oauth2.client.registration.keycloak.client-name=iw-user-service-client
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.keycloak.scope=openid, profile, email
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9090/realms/prose